// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThroughTheSnow_Yuv_Sap_Dani.Server.Data;

namespace ThroughTheSnow_Yuv_Sap_Dani.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220625092833_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("ThroughTheSnow_Yuv_Sap_Dani.Shared.Entities.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameInstruction")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublish")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("ThroughTheSnow_Yuv_Sap_Dani.Shared.Entities.Item", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ThroughTheSnow_Yuv_Sap_Dani.Shared.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ThroughTheSnow_Yuv_Sap_Dani.Shared.Entities.Game", b =>
                {
                    b.HasOne("ThroughTheSnow_Yuv_Sap_Dani.Shared.Entities.User", "GameUser")
                        .WithMany("UserGames")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameUser");
                });

            modelBuilder.Entity("ThroughTheSnow_Yuv_Sap_Dani.Shared.Entities.Item", b =>
                {
                    b.HasOne("ThroughTheSnow_Yuv_Sap_Dani.Shared.Entities.Game", "ItemGame")
                        .WithMany("GameItems")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemGame");
                });

            modelBuilder.Entity("ThroughTheSnow_Yuv_Sap_Dani.Shared.Entities.Game", b =>
                {
                    b.Navigation("GameItems");
                });

            modelBuilder.Entity("ThroughTheSnow_Yuv_Sap_Dani.Shared.Entities.User", b =>
                {
                    b.Navigation("UserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
